"""add form_tag to newsletter subscriber

Revision ID: d8b82b3f402e
Revises: 0734e4675626
Create Date: 2025-08-03 18:53:35.379938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b82b3f402e'
down_revision = '0734e4675626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_tag', sa.String(length=50), nullable=False, server_default='newsletter'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.drop_column('form_tag')

    # ### end Alembic commands ###